require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Include:
    - lib/**/*.rb

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 160
  Exclude:
    - config/routes.rb

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

Lint/UnusedMethodArgument:
  Exclude:
    - app/interactors/**/*.rb

Lint/UselessAccessModifier:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 110

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 15

RSpec/ExampleLength:
  Max: 80

RSpec/MultipleExpectations:
  Max: 12

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/CollectionMethods:
  PreferredMethods:
    find: "detect"
