sudo: required
dist: trusty
language: ruby
bundler_args: "--without production"
services:
- postgresql
- redis
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-server-dev-9.6
before_install:
- gem update --system
- gem install bundler
- script/install-partman
before_script:
- bundle exec danger
- sudo service postgresql restart 9.6
script:
  - rake db:test:prepare_all
  - RAILS_ENV=test rake spec
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: "TUfn92zHpVdzeqbeec+R+ssXR7hgYamRU4QiMbo/vdX52gUo1BMqW98lzEzVcLMRUWdd6bzU5INzUa9wfhLs6oFRXZP+F6odq1zZSIj2zMizzOdl5tihBEmvRxz3nbylJbIy2QfZu3MiZ4lX/vGcr7z0MY7qMYWch1Rs8hITru4pI5zt3CHvx160cKjtcdVOoYt6WKW4c+D3YTpEUr7Beez3pdlg/G4gFY4eoLUZXe34lIkjrfoAJhwPrYcqybdq3oyDIHC6S2OnQEMmthi5v7162gnTbQIpxilqZDdOlOD7TbX7j4lB/7tvkL8pg6TiQbswky6t/ul/XRdOEv51IABhbqF8vGFkbQYCrrnR8Sbu5Swlx4wJIx/8Fu6RNeRZR9ncjP2wmStCLdoVUF+6GmX7lNO46tYt+2lGZe3e3Rau6XkN34LQH3OyeqShS6jMFtKmZ92d/ANjlq6VGTDjtfZ3q+XvL1aXkOG3r8HI3kcAYGpveJhDDatWV9e+/ceIZBAXJDbfDCO5lYtPbJ1PMtzZhYxDEIIz3ZabUUchEhFJ79KdH4m1ffUbpS7/EbSA+6yjD4EQyEI3piS2+OqWAsn5bqRDNl2zzH9cN7ugMtn8OD0NLbnvmCnTMidxhTql7Bb/XlQUemMnLGvPtoEYZzX/IK6UecYGvGCqwOifl5E="
