sudo: required
dist: trusty
language: ruby
bundler_args: "--without production"
services:
- postgresql
- redis
addons:
  postgresql: '9.6'
before_script:
- bundle exec danger
- sudo apt-get install postgresql-server-dev-all postgresql-common
- curl -L -O https://github.com/keithf4/pg_partman/archive/v2.6.2.tar.gz
- tar -zxvf v2.6.2.tar.gz
- cd pg_partman-2.6.2 && sudo make NO_BGW=1 install
script:
  - rake aggregation:db:test:prepare
  - RAILS_ENV=test rake db:setup spec
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: CXVvCbNheYXvpLc8u0m47caos+yJJAjltMs+JEw4nQcG1ltaWNjkSDH9gePpQ6xO5hm9NEzvXej09T3ye6QPA51jBXFODE0uwOgSvkCmA+H+IuLpaLuEwKLbEqxuB9sDfq7ZyHeX9fWcXXNax7ttgJRy0Z499ZfVfOb6vyMggYWZlTIrBCGERSUK6V5ud11Es5C+w6tZ9YZKWP8QMhC0/MIxYOq1nc6w4hAWfe6+DFsdbfAOQFJEDFL738Y4TWDMxHMUP4Y9Ru2w1awQ5TlC/5v0X74RLjXIfCVM9cH6GoXvmFGAhpaSGFYRDE1mC4mXIwLQdpjKKzakH1+MXeSbarserjM0so/2DLC2ifjDsBmQ0c908XRKmfgtK8HMeo/Dmp5S/xg3LxQoPNrCZQbYLMm7MhCvt3rYpM8EBb0jgGNv6hRORedNoQGUSDTr8BvL40qAicW5tY2eT4POym3idHaoPiE0bCR9JPxR5qQVHpsNlFJsJ7iMGJquReTZ9xXLp2rnJCGb7oLo66FRes6s8wTeraLfIpVfAIgA1BHly1mZn+ElRM5zGozshEClXrXjW7oxG8iQMkX9x7nQVV/yxtIYHnBHw5ENuFh6zG5nggouTz/B+mCz8hi3yfjoCwsEaEuzb++eu3Ox1rzjXAYnV40OhEDRUrNjEu+4d+4Y90k=
